# -*- coding: utf-8 -*-
"""image to text.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z905XBPqwSyEo7c30ED7GN7VHyaqzkHU
"""

# from PIL import Image
# import pytesseract
# import requests
# from io import BytesIO

# # URL of the image you want to extract text from
# image_url = "https://disney.images.edge.bamgrid.com/ripcut-delivery/v1/variant/disney/9309BAAF6D290B0DF641EEB390BC4AE9582F51637CC7032AF44D7861BAF61600/scale?width=240"

# # Download the image from the URL
# response = requests.get(image_url)
# img = Image.open(BytesIO(response.content))

# # Set the Tesseract executable path (you might not need this step)
# pytesseract.pytesseract.tesseract_cmd = '/usr/bin/tesseract'

# # Extract text from the image
# text = pytesseract.image_to_string(img)

# # Display the extracted text
# print(text)

import csv
from PIL import Image
import pytesseract
import requests
from io import BytesIO

pytesseract.pytesseract.tesseract_cmd = '/usr/bin/tesseract'

def extract_text_from_image(image_url):
    response = requests.get(image_url)
    img = Image.open(BytesIO(response.content))

    text = pytesseract.image_to_string(img)
    return text

updated_rows = []
with open('movie_data.csv', 'r', encoding='utf-8') as file:
    reader = csv.reader(file)
    headers = next(reader)
    updated_rows.append(headers)

    for row in reader:
        movie_name, image_link = row
        extracted_text = extract_text_from_image(image_link)
        updated_rows.append([movie_name, extracted_text])

with open('movie_data.csv', 'w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerows(updated_rows)

!pip install pytesseract
!apt-get install tesseract-ocr

